name: Build and Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
            
      - name: Build
        run: dotnet build src/AnkiNet/AnkiNet.csproj --configuration Release
        
      - name: Package
        run: >
          dotnet pack src/AnkiNet/AnkiNet.csproj --no-restore --no-build --configuration Release 
          -p:PackageVersion=${{ github.ref_name }} --output .
        
      - name: Publish
        run: >
          dotnet nuget push Anki.NET.${{ github.ref_name }}.nupkg 
          -s https://nuget.pkg.github.com/sirush/index.json 
          -k ${{ secrets.PACKAGE }}
